# Generated by Django 2.0.4 on 2018-11-06 12:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_a', ckeditor.fields.RichTextField()),
                ('content_a', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_s', models.CharField(max_length=100)),
                ('content_s', models.TextField()),
            ],
        ),
    ]
