# Generated by Django 2.0.4 on 2018-11-08 07:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='title_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='content_s',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
